# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build package
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm install --global pnpm@latest-8
      displayName: 'Install pnpm'

    - script: pnpm install
      displayName: 'Install dependencies'

    - script: pnpm run build
      displayName: 'Build package'

    - publish: $(System.DefaultWorkingDirectory)
      artifact: autharmor-sdk

    - task: DownloadSecureFile@1
      name: envFile
      displayName: 'Download development environment file'
      inputs:
        secureFile: 'autharmor-sdk.environment.development.ts'

    - script: |
        rm $(System.DefaultWorkingDirectory)/src/environment/environment.ts
        mv $(envFile.secureFilePath) $(System.DefaultWorkingDirectory)/src/environment/environment.ts
      displayName: 'Install development environment file'

    - script: pnpm run build
      displayName: 'Build development package'

    - publish: $(System.DefaultWorkingDirectory)
      artifact: autharmor-sdk-dev

