# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: build_package
    displayName: 'Build package'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm install --global pnpm@latest-8
      displayName: 'Install pnpm'

    - script: pnpm install
      displayName: 'Install dependencies'

    - script: pnpm run build
      displayName: 'Build package'

    - task: CopyFiles@2
      displayName: 'Stage artifact files'
      inputs:
        contents: |
          dist/**
          package.json
          .npmrc
          README.md
        targetFolder: $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: autharmor-sdk
      displayName: 'Publish package'

  - deployment: deploy_to_npm
    displayName: 'Deploy to npm registry'
    dependsOn: build_package
    environment: sdk-production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: autharmor-sdk
          - task: npmAuthenticate@0
            inputs:
              workingFile: $(Pipeline.Workspace)/autharmor-sdk/.npmrc
              customEndpoint: 'npm publish connection'
          - script: npm publish --access public
            workingDirectory: $(Pipeline.Workspace)/autharmor-sdk-dev/

  - job: build_dev_package
    displayName: 'Build development package'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm install --global pnpm@latest-8
      displayName: 'Install pnpm'

    - script: pnpm install
      displayName: 'Install dependencies'

    - task: DownloadSecureFile@1
      name: envFile
      displayName: 'Download development environment file'
      inputs:
        secureFile: 'autharmor-sdk.environment.development.ts'

    - script: |
        rm $(System.DefaultWorkingDirectory)/src/environment/environment.ts
        mv $(envFile.secureFilePath) $(System.DefaultWorkingDirectory)/src/environment/environment.ts
      displayName: 'Install development environment file'

    - script: pnpm run build
      displayName: 'Build package'

    - script: mv -f .dev.npmrc .npmrc
      displayName: 'Use development .npmrc file'

    - task: CopyFiles@2
      displayName: 'Stage artifact files'
      inputs:
        contents: |
          dist/**
          package.json
          .npmrc
          README.md
        targetFolder: $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: autharmor-sdk-dev
      displayName: 'Publish package'

  - deployment: deploy_dev_to_artifacts
    displayName: 'Deploy development package to Azure Artifacts'
    dependsOn: build_dev_package
    environment: sdk-development
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: autharmor-sdk-dev
          - task: npmAuthenticate@0
            inputs:
              workingFile: $(Pipeline.Workspace)/autharmor-sdk-dev/.npmrc
          - script: npm publish
            workingDirectory: $(Pipeline.Workspace)/autharmor-sdk-dev/
